[tool.poetry]
name = "metadamage"
version = "0.0.0"
description = "Metagenomics Ancient Damage: metadamage"
authors = ["Christian Michelsen <christianmichelsen@gmail.com>"]
license = "MIT"
keywords = ['metadamage', 'metagenomics', 'ancient damage', 'DNA damage']
repository = "https://github.com/ChristianMichelsen/metadamage"
readme = "README.md"
include = ["metadamage/style.mplstyle", 'pyproject.toml']
exclude = ["logs/log*"]


[tool.poetry.dependencies]
python = "^3.8"
pip = "^20.3.3"
numpyro = "^0.4.1"
pandas = "^1.2.0"
matplotlib = "^3.3.3"
pyarrow = "^2.0.0"
rich = "^9.8.1"
typer = {extras = ["all"], version = "^0.3.2"}
click-help-colors = "^0.9"
poetry-dynamic-versioning = "^0.12.1"
timeout-decorator = "^0.5.0"
iminuit = "^2.4.0"
numba = { version = "^0.53.1", python = ">=3.8,<3.10" }
pre-commit = "^2.13.0"


[tool.poetry.dev-dependencies]
pytest = "^4.6"
flake8 = "^3.8.4"
ipykernel = "^5.4.3"
black = {version = "^20.8b1", allow-prereleases = true}
pylint = "^2.6.0"
pytest-cov = "^2.11.0"
isort = "^5.7.0"
coverage = "^5.3.1"
poethepoet = "^0.9.0"

[tool.poetry.scripts]
metadamage = "metadamage.cli:cli_main"

[tool.poetry-dynamic-versioning]
enable = true
style = "semver"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
test   = "pytest ."
isort = "isort ."
format = "black ."
black = ["format"]
clean = """
# Multiline commands including comments work too. Unescaped whitespace is ignored.
rm -rf .coverage
       .mypy_cache
       .pytest_cache
       metadamage/logs/*
       dist
       ./**/__pycache__
"""
build = "poetry build"
_publish = "poetry publish"
_git_push_with_tags = "git push --follow-tags"
git_release = ["_git_push_with_tags"]

lint = ["isort", "black"]
test_and_lint = ["test", "lint"]

# poe release
release = ["test", "isort", "black", "clean", "build", "_publish", "git_release"]
publish = ['release']

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | tests/.*/setup.py
)/
'''
